templateScript: /tddirect-site/templates/pages/default.ftl
renderType: site
visible: true
type: default
title: Default
dialog: tddirect-site:pages/page-properties
areas:
  head:
    templateScript: /tddirect-site/templates/components/head.ftl
    type: noComponent
  header:
    templateScript: /tddirect-site/templates/components/header.ftl
    type: noComponent
    areas:
      navigation:
        templateScript: /tddirect-site/templates/components/navigation.ftl
        type: noComponent        
      mobile-menu:
        templateScript: /tddirect-site/templates/components/mobile-menu.ftl
        type: noComponent        
  footer:
    templateScript: /tddirect-site/templates/components/footer.ftl
    type: noComponent
    inheritance:
     enabled: true
     components: all
    areas:
      help:
        templateScript: /tddirect-site/templates/components/help.ftl
        type: noComponent
      webchat:
        templateScript: /tddirect-site/templates/components/webchat.ftl
        type: noComponent
      connect:
        templateScript: /tddirect-site/templates/components/connect.ftl
        type: noComponent
  analytics:
    templateScript: /tddirect-site/templates/components/analytics.ftl
    type: noComponent
  cookie:
    templateScript: /tddirect-site/templates/components/cookie.ftl
    type: noComponent
  ii-notice:
    templateScript: /tddirect-site/templates/components/ii-notice.ftl
    type: noComponent
  alert:
    templateScript: /tddirect-site/templates/components/alert.ftl
    type: noComponent          
  main-top:
    renderType: site
    maxComponents: 1
    editable: true
    availableComponents:
      main-top:
        id: tddirect-site:components/main-top
      main-top-alt:
        id: tddirect-site:components/main-top-alt
    inheritance:
      enabled: false
      components: all
  section-choices:
    renderType: site
    maxComponents: 1
    availableComponents:
      basic:
        id: tddirect-site:components/section-choices
    inheritance:
      enabled: true
      components: all
  main-content:
     renderType: site
     availableComponents:
      main:
        id: tddirect-site:components/main
      list:
        id: tddirect-site:components/list        
      panels:
        id: tddirect-site:components/panels
      accordion:
        id: tddirect-site:components/accordion 
      tabs:
        id: tddirect-site:components/tabs
      chart:
        id: tddirect-site:components/chart        
      jisa-calculator:
        id: tddirect-site:components/jisa-calculator
      risers-fallers:
        id: tddirect-site:components/risers-fallers
      best-buys:
        id: tddirect-site:components/best-buys
      quote:
        id: tddirect-site:components/quote                 
      pure360Sipp:
        id: tddirect-site:components/pure360Sipp                 
  radios:
    templateScript: /tddirect-site/templates/components/radios.ftl
    type: noComponent
  sidebar:
     renderType: site
     availableComponents:
      sidebar:
        id: tddirect-site:components/sidebar
      pure360:
        id: tddirect-site:components/pure360        